# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c7890fe831bf9559d7629588a2c963cace66564692a9181f543dad8c84ac6ef947c2fb770c40f3fb2c44c9786c1a32a3363437e6002ae779d8954cc8ce6d83c

test:
  secret_key_base: 4f8aacc3f536fd1d1a3479e7b489e0262b5516d2feb940ce9c87023953818e50f5c02b658c3370eb343726e594d56875ddf78208cbce9777d364a730cf39d5c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
